//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfImageViewer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TumblThree Image Viewer")]
        public string ApplicationTitle {
            get {
                return ((string)(this["ApplicationTitle"]));
            }
            set {
                this["ApplicationTitle"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public string BackgroundColor
        {
            get
            {
                return ((string)(this["BackgroundColor"]));
            }
            set
            {
                this["BackgroundColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CloseOnLostFocus
        {
            get
            {
                return ((bool)(this["CloseOnLostFocus"]));
            }
            set
            {
                this["CloseOnLostFocus"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ImageDurationSeconds
        {
            get
            {
                return ((int)(this["ImageDurationSeconds"]));
            }
            set
            {
                this["ImageDurationSeconds"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".bmp,.gif,.jpeg,.jpg,.png,.tif,.tiff")]
        public string IncludedFileExtensions
        {
            get
            {
                return ((string)(this["IncludedFileExtensions"]));
            }
            set
            {
                this["IncludedFileExtensions"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public string MsgColor
        {
            get
            {
                return ((string)(this["MsgColor"]));
            }
            set
            {
                this["MsgColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double MsgFadeoutSeconds
        {
            get
            {
                return ((double)(this["MsgFadeoutSeconds"]));
            }
            set
            {
                this["MsgFadeoutSeconds"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RunAnimatedGifs
        {
            get
            {
                return ((bool)(this["RunAnimatedGifs"]));
            }
            set
            {
                this["RunAnimatedGifs"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowHelpOnLoad
        {
            get
            {
                return ((bool)(this["ShowHelpOnLoad"]));
            }
            set
            {
                this["ShowHelpOnLoad"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double ZoomMax
        {
            get
            {
                return ((double)(this["ZoomMax"]));
            }
            set
            {
                this["ZoomMax"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double ZoomMin {
            get {
                return ((double)(this["ZoomMin"]));
            }
            set {
                this["ZoomMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.25")]
        public double ZoomStep {
            get {
                return ((double)(this["ZoomStep"]));
            }
            set {
                this["ZoomStep"] = value;
            }
        }
    }
}
